version: '3'

services:
  kyc-provider:
    build:
      context: .
      dockerfile: ./kyc-provider/Dockerfile
    ports:
      - 8000:8000
    environment:
      PORT: 8000
  verifier:
    build:
      context: .
      dockerfile: ./verifier/Dockerfile
    ports:
      - 8001:8001
    environment:
      PORT: 8001
    depends_on:
      - kyc-provider